FROM python:3-slim-bullseye

WORKDIR /src

COPY /src .
COPY requirements.txt /src

RUN apt update \
		&& apt upgrade -y\
    && pip3 install -r requirements.txt \
    && apt -y autoremove \
    && apt -y autoclean \
    && apt -y clean \
    && rm -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/* \
    && pip cache purge \
    && rm -rf /root/.cache/*

CMD ["uvicorn", "api.app:app", "--host=0.0.0.0","--port=8000","--reload"]
